name: Cache Dependencies

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cache-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Python dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python3.9/site-packages
        key: cache-2b11042-${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          cache-2b11042-${{ runner.os }}-python-
          cache-2b11042-
    
    - name: prime-cache-2b11042
      run: |
        echo "Cache hit status: ${{ steps.cache-deps.outputs.cache-hit }}"
        if [ "${{ steps.cache-deps.outputs.cache-hit }}" == 'true' ]; then
          echo "✅ Cache HIT - Dependencies restored from cache"
          echo "Verifying installed packages:"
          pip list
        else
          echo "❌ Cache MISS - Installing dependencies fresh"
          pip install -r requirements.txt
          echo "Dependencies installed successfully"
        fi
